//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "auxbase3.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_spp_Tower_F" createvehicle [3524.0700684,4923.129883,0.037735];
_obj setposATL [3524.0700684,4923.129883,0.037735];
_obj setdir 199.559;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_addon" createvehicle [3520.639893,4921.00976563,42.7973];
_obj setposATL [3520.639893,4921.00976563,42.7973];
_obj setdir 200.161;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3485.358643,4907.817871,-0.358932];
_obj setposATL [3485.358643,4907.817871,-0.358932];
_obj setdir 195.046;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3490.358643,4906.42041,-0.380417];
_obj setposATL [3490.358643,4906.42041,-0.380417];
_obj setdir 195.068;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3495.343506,4905.0639648,-0.0505981];
_obj setposATL [3495.343506,4905.0639648,-0.0505981];
_obj setdir 195.207;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3500.391602,4903.696777,-0.271255];
_obj setposATL [3500.391602,4903.696777,-0.271255];
_obj setdir 195.352;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3505.38208,4902.277832,-0.327225];
_obj setposATL [3505.38208,4902.277832,-0.327225];
_obj setdir 196.011;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3488.019043,4926.223633,-0.506241];
_obj setposATL [3488.019043,4926.223633,-0.506241];
_obj setdir 289.353;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3491.719971,4929.22998,-0.315521];
_obj setposATL [3491.719971,4929.22998,-0.315521];
_obj setdir 14.932;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3486.306641,4921.292969,-0.399887];
_obj setposATL [3486.306641,4921.292969,-0.399887];
_obj setdir 287.69;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3483.199219,4911.292969,-0.491592];
_obj setposATL [3483.199219,4911.292969,-0.491592];
_obj setdir 286.091;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3484.691406,4916.34375,-0.220291];
_obj setposATL [3484.691406,4916.34375,-0.220291];
_obj setdir 287.759;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3509.810547,4899.936523,-0.639771];
_obj setposATL [3509.810547,4899.936523,-0.639771];
_obj setdir 221.127;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3496.830078,4927.799805,-0.284424];
_obj setposATL [3496.830078,4927.799805,-0.284424];
_obj setdir 16.771;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3494.429932,4940.799805,0.0557251];
_obj setposATL [3494.429932,4940.799805,0.0557251];
_obj setdir 16.009;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3499.404297,4939.349121,-0.533768];
_obj setposATL [3499.404297,4939.349121,-0.533768];
_obj setdir 15.464;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3504.365479,4937.850098,-0.347198];
_obj setposATL [3504.365479,4937.850098,-0.347198];
_obj setdir 16.712;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3514.273926,4934.900391,-0.201584];
_obj setposATL [3514.273926,4934.900391,-0.201584];
_obj setdir 15.866;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3519.186523,4933.216309,-0.301102];
_obj setposATL [3519.186523,4933.216309,-0.301102];
_obj setdir 21.521;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3523.987793,4931.198242,-0.138382];
_obj setposATL [3523.987793,4931.198242,-0.138382];
_obj setdir 24.284;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3528.887451,4929.715332,-0.459961];
_obj setposATL [3528.887451,4929.715332,-0.459961];
_obj setdir 11.463;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3533.669189,4927.793457,-0.94902];
_obj setposATL [3533.669189,4927.793457,-0.94902];
_obj setdir 32.552;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3537.289063,4924.114746,-0.490799];
_obj setposATL [3537.289063,4924.114746,-0.490799];
_obj setdir 58.888;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3540.692139,4920.73584,-0.293289];
_obj setposATL [3540.692139,4920.73584,-0.293289];
_obj setdir 27.812;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3544.927979,4916.936523,-0.0119629];
_obj setposATL [3544.927979,4916.936523,-0.0119629];
_obj setdir 57.162;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3514.154053,4897.0712891,-0.391281];
_obj setposATL [3514.154053,4897.0712891,-0.391281];
_obj setdir 204.598;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3519.124268,4895.411621,-0.434799];
_obj setposATL [3519.124268,4895.411621,-0.434799];
_obj setdir 194.011;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3524.0837402,4893.936035,-0.862076];
_obj setposATL [3524.0837402,4893.936035,-0.862076];
_obj setdir 200.263;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3529.0397949,4893.67041,-0.472183];
_obj setposATL [3529.0397949,4893.67041,-0.472183];
_obj setdir 163.911;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3533.85376,4895.659668,-0.237701];
_obj setposATL [3533.85376,4895.659668,-0.237701];
_obj setdir 151.49;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3537.918457,4898.820801,-0.48967];
_obj setposATL [3537.918457,4898.820801,-0.48967];
_obj setdir 133.029;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3541.378418,4902.727051,-0.432373];
_obj setposATL [3541.378418,4902.727051,-0.432373];
_obj setdir 130.451;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3548.441162,4913.521973,-0.13945];
_obj setposATL [3548.441162,4913.521973,-0.13945];
_obj setdir 32.844;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "BagBunker_Tower_F" createvehicle [3494.540039,4924.430176,-0.00640869];
_obj setposATL [3494.540039,4924.430176,-0.00640869];
_obj setdir 105.334;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3541.9375,4920.125488,0.062088];
_obj setposATL [3541.9375,4920.125488,0.062088];
_obj setdir 26.943;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3509.335205,4936.396973,-0.807068];
_obj setposATL [3509.335205,4936.396973,-0.807068];
_obj setdir 16.008;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_BagBunker_Tower_F" createvehicle [3500.590088,4922.77002,-0.208649];
_obj setposATL [3500.590088,4922.77002,-0.208649];
_obj setdir 286.946;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "CamoNet_OPFOR_open_F" createvehicle [3494.570068,4933.640137,1.05501];
_obj setposATL [3494.570068,4933.640137,1.05501];
_obj setdir 285.483;
_obj setVariable ["R3F_LOG_disabled", true, true]; "this allowDamage false;"; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3501.97998,4926.189941,-0.283539];
_obj setposATL [3501.97998,4926.189941,-0.283539];
_obj setdir 15.226;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3507.0600586,4924.919922,-0.284821];
_obj setposATL [3507.0600586,4924.919922,-0.284821];
_obj setdir 13.734;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3511.399902,4921.180176,-0.28447];
_obj setposATL [3511.399902,4921.180176,-0.28447];
_obj setdir 107.639;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3507.649902,4911.379883,-0.285614];
_obj setposATL [3507.649902,4911.379883,-0.285614];
_obj setdir 109.192;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3506.0200195,4906.560059,-0.282593];
_obj setposATL [3506.0200195,4906.560059,-0.282593];
_obj setdir 107.303;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall1_F" createvehicle [3510.169922,4924.149902,-0.302872];
_obj setposATL [3510.169922,4924.149902,-0.302872];
_obj setdir 13.552;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall1_F" createvehicle [3511.409912,4923.870117,-0.304474];
_obj setposATL [3511.409912,4923.870117,-0.304474];
_obj setdir 11.123;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Hbarrier_5_F" createvehicle [3490.646484,4937.616699,0.109329];
_obj setposATL [3490.646484,4937.616699,0.109329];
_obj setdir 107.059;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.328,4.328] call BIS_fnc_setPitchBank;
_obj = "Land_Hbarrier_5_F" createvehicle [3489.0153809,4932.236328,-0.0867615];
_obj setposATL [3489.0153809,4932.236328,-0.0867615];
_obj setdir 106.332;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.415,4.415] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3545.0383301,4903.666016,-0.454956];
_obj setposATL [3545.0383301,4903.666016,-0.454956];
_obj setdir 206.233;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3549.67334,4901.414063,-0.404419];
_obj setposATL [3549.67334,4901.414063,-0.404419];
_obj setdir 205.841;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3552.790039,4910.666016,-0.373093];
_obj setposATL [3552.790039,4910.666016,-0.373093];
_obj setdir 32.918;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3541.349609,4916.0957031,-0.0518799];
_obj setposATL [3541.349609,4916.0957031,-0.0518799];
_obj setdir 313.445;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3535.923584,4911.500488,-0.304199];
_obj setposATL [3535.923584,4911.500488,-0.304199];
_obj setdir 327.563;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-0.062,-0.062] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [3535.189941,4917.540039,-0.206558];
_obj setposATL [3535.189941,4917.540039,-0.206558];
_obj setdir 309.163;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [3511.919922,4906.0400391,-0.206558];
_obj setposATL [3511.919922,4906.0400391,-0.206558];
_obj setdir 19.315;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_JumpTarget_F" createvehicle [3524.350098,4906.339844,0];
_obj setposATL [3524.350098,4906.339844,0];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Mound01_8m_F" createvehicle [3545.219971,4909.290039,-0.590759];
_obj setposATL [3545.219971,4909.290039,-0.590759];
_obj setdir 301.246;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Mound01_8m_F" createvehicle [3549.80249,4907.263672,-0.601669];
_obj setposATL [3549.80249,4907.263672,-0.601669];
_obj setdir 118.275;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Mound01_8m_F" createvehicle [3553.0600586,4905.560059,-0.563019];
_obj setposATL [3553.0600586,4905.560059,-0.563019];
_obj setdir 117.173;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Mound01_8m_F" createvehicle [3537.544189,4907.46582,-0.552475];
_obj setposATL [3537.544189,4907.46582,-0.552475];
_obj setdir 53.805;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3537.389893,4895.5,0.105484];
_obj setposATL [3537.389893,4895.5,0.105484];
_obj setdir 321.723;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3542.658936,4900.127441,-0.151245];
_obj setposATL [3542.658936,4900.127441,-0.151245];
_obj setdir 314.245;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0.991,0.991] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3530.962158,4891.440918,0.32724];
_obj setposATL [3530.962158,4891.440918,0.32724];
_obj setdir 344.18;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,8.974,8.974] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3523.415771,4890.450195,0.106094];
_obj setposATL [3523.415771,4890.450195,0.106094];
_obj setdir 4.43;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,8.974,8.974] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3516.127197,4892.14502,-0.315292];
_obj setposATL [3516.127197,4892.14502,-0.315292];
_obj setdir 16.236;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,8.105,8.105] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3509.601318,4894.954102,0.212234];
_obj setposATL [3509.601318,4894.954102,0.212234];
_obj setdir 33.946;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,8.974,8.974] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3503.306152,4898.577148,0.265533];
_obj setposATL [3503.306152,4898.577148,0.265533];
_obj setdir 20.507;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,8.883,8.883] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3489.381104,4903.896973,0.0817261];
_obj setposATL [3489.381104,4903.896973,0.0817261];
_obj setdir 19.68;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,13.999,13.999] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3496.32251,4901.257813,0.341522];
_obj setposATL [3496.32251,4901.257813,0.341522];
_obj setdir 19.522;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,11.719,11.719] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3484.78125,4905.256836,0.83812];
_obj setposATL [3484.78125,4905.256836,0.83812];
_obj setdir 19.869;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,11.824,11.824] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3483.209473,4906.0644531,0.968597];
_obj setposATL [3483.209473,4906.0644531,0.968597];
_obj setdir 26.246;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,11.954,11.954] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3481.708252,4907.124023,0.963577];
_obj setposATL [3481.708252,4907.124023,0.963577];
_obj setdir 53.236;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,12.086,12.086] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3480.787598,4908.813965,0.799057];
_obj setposATL [3480.787598,4908.813965,0.799057];
_obj setdir 71.996;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,12.373,12.373] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3480.999512,4910.895996,0.0937805];
_obj setposATL [3480.999512,4910.895996,0.0937805];
_obj setdir 94.798;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.801,4.801] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3482.550049,4915.52002,0.0119629];
_obj setposATL [3482.550049,4915.52002,0.0119629];
_obj setdir 108.834;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3484.22998,4922.609863,0.00523376];
_obj setposATL [3484.22998,4922.609863,0.00523376];
_obj setdir 111.452;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3486.280029,4927.839844,-0.00119019];
_obj setposATL [3486.280029,4927.839844,-0.00119019];
_obj setdir 291.155;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3547.883789,4918.00439453,0.22052];
_obj setposATL [3547.883789,4918.00439453,0.22052];
_obj setdir 280.993;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3510.250732,4939.587402,0.133835];
_obj setposATL [3510.250732,4939.587402,0.133835];
_obj setdir 11.295;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [3503.160889,4941.137695,0.177002];
_obj setposATL [3503.160889,4941.137695,0.177002];
_obj setdir 11.295;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3492.0966797,4941.0771484,0.0175171];
_obj setposATL [3492.0966797,4941.0771484,0.0175171];
_obj setdir 108.291;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium_F" createvehicle [3493.262939,4942.495605,-0.164536];
_obj setposATL [3493.262939,4942.495605,-0.164536];
_obj setdir 141.848;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Hbarrier_5_F" createvehicle [3489.326416,4938.0664063,0.100815];
_obj setposATL [3489.326416,4938.0664063,0.100815];
_obj setdir 107.059;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.328,4.328] call BIS_fnc_setPitchBank;
_obj = "Land_Hbarrier_5_F" createvehicle [3487.446533,4932.766602,-0.0870209];
_obj setposATL [3487.446533,4932.766602,-0.0870209];
_obj setdir 107.059;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.328,4.328] call BIS_fnc_setPitchBank;
_obj = "CamoNet_OPFOR_open_F" createvehicle [3491.26001,4911.680176,1.38553];
_obj setposATL [3491.26001,4911.680176,1.38553];
_obj setdir 216.832;
_obj setVariable ["R3F_LOG_disabled", true, true]; "this allowDamage false;"; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "TargetP_Zom_F" createvehicle [3508.939941,4904.890137,4.14525];
_obj setposATL [3508.939941,4904.890137,4.14525];
_obj setdir 49.892;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "TargetP_Zom_F" createvehicle [3535.340088,4914.470215,4.151];
_obj setposATL [3535.340088,4914.470215,4.151];
_obj setdir 326.296;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "TargetP_Zom_F" createvehicle [3540.0,4916.00976563,0.000320435];
_obj setposATL [3540.0,4916.00976563,0.000320435];
_obj setdir 334.056;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "TargetP_Zom_F" createvehicle [3517.860107,4925.77002,0.00167847];
_obj setposATL [3517.860107,4925.77002,0.00167847];
_obj setdir 31.607;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [3488.413574,4927.47168,-0.506241];
_obj setposATL [3488.413574,4927.47168,-0.506241];
_obj setdir 289.353;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
