//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "slitchbaseplpha.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_HBarrier_Big_F" createvehicle [5134.600098,4319.649902,0.197647];
_obj setposATL [5134.600098,4319.649902,0.197647];
_obj setdir 95.338;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrier_Big_F" createvehicle [5134.319824,4313.200195,-1.04938];
_obj setposATL [5134.319824,4313.200195,-1.04938];
_obj setdir 278.471;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrier_Big_F" createvehicle [5133.140137,4304.799805,-0.188751];
_obj setposATL [5133.140137,4304.799805,-0.188751];
_obj setdir 279.807;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5133.990234,4311.259766,1.04303];
_obj setposATL [5133.990234,4311.259766,1.04303];
_obj setdir 97.699;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrierBig_F" createvehicle [5132.00976563,4296.419922,0.638718];
_obj setposATL [5132.00976563,4296.419922,0.638718];
_obj setdir 279.088;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrierBig_F" createvehicle [5132.77002,4302.779785,1.82541];
_obj setposATL [5132.77002,4302.779785,1.82541];
_obj setdir 278.394;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrierBig_F" createvehicle [5131.569824,4292.259766,-0.969757];
_obj setposATL [5131.569824,4292.259766,-0.969757];
_obj setdir 279.088;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrierBig_F" createvehicle [5131.680176,4294.279785,2.48502];
_obj setposATL [5131.680176,4294.279785,2.48502];
_obj setdir 100.076;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank; 
_obj = "Land_HBarrierBig_F" createvehicle [5128.879883,4275.660156,-0.614532];
_obj setposATL [5128.879883,4275.660156,-0.614532];
_obj setdir 281.274;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5130.450195,4283.790039,-0.58989];
_obj setposATL [5130.450195,4283.790039,-0.58989];
_obj setdir 279.088;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5130.950195,4288.0297852,0.968948];
_obj setposATL [5130.950195,4288.0297852,0.968948];
_obj setdir 279.088;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5129.470215,4279.669922,1.16269];
_obj setposATL [5129.470215,4279.669922,1.16269];
_obj setdir 282.754;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5132.669922,4300.450195,-1.66602];
_obj setposATL [5132.669922,4300.450195,-1.66602];
_obj setdir 98.238;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5130.660156,4285.959961,2.77492];
_obj setposATL [5130.660156,4285.959961,2.77492];
_obj setdir 279.275;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5129.100098,4277.640137,2.9157];
_obj setposATL [5129.100098,4277.640137,2.9157];
_obj setdir 102.31;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5123.120117,4272.25,-1.63028];
_obj setposATL [5123.120117,4272.25,-1.63028];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5125.0800781,4272.439941,0.664154];
_obj setposATL [5125.0800781,4272.439941,0.664154];
_obj setdir 359.632;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5129.180176,4277.689941,1.15091];
_obj setposATL [5129.180176,4277.689941,1.15091];
_obj setdir 282.978;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5116.339844,4272.350098,1.1299];
_obj setposATL [5116.339844,4272.350098,1.1299];
_obj setdir 359.632;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5116.589844,4272.240234,-0.693817];
_obj setposATL [5116.589844,4272.240234,-0.693817];
_obj setdir 2.128;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5124.970215,4272.649902,2.42029];
_obj setposATL [5124.970215,4272.649902,2.42029];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5108.140137,4272.180176,-1.27415];
_obj setposATL [5108.140137,4272.180176,-1.27415];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5107.910156,4272.120117,0.591003];
_obj setposATL [5107.910156,4272.120117,0.591003];
_obj setdir 0.013;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5099.439941,4271.569824,1.23712];
_obj setposATL [5099.439941,4271.569824,1.23712];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5099.459961,4271.660156,-0.632431];
_obj setposATL [5099.459961,4271.660156,-0.632431];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5091.540039,4273.810059,0.0162964];
_obj setposATL [5091.540039,4273.810059,0.0162964];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5091.589844,4274.259766,2.1152];
_obj setposATL [5091.589844,4274.259766,2.1152];
_obj setdir 43.36;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5085.120117,4279.680176,0.0162964];
_obj setposATL [5085.120117,4279.680176,0.0162964];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5085.129883,4279.77002,2.1152];
_obj setposATL [5085.129883,4279.77002,2.1152];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5078.700195,4285.25,1.108];
_obj setposATL [5078.700195,4285.25,1.108];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5078.689941,4285.160156,-0.990906];
_obj setposATL [5078.689941,4285.160156,-0.990906];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5072.259766,4290.740234,-0.212891];
_obj setposATL [5072.259766,4290.740234,-0.212891];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5072.25,4290.649902,-2.3118];
_obj setposATL [5072.25,4290.649902,-2.3118];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_House_V3_F" createvehicle [5124.930176,4320.319824,0.662964];
_obj setposATL [5124.930176,4320.319824,0.662964];
_obj setdir 94.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [5121.910156,4279.129883,0.14682];
_obj setposATL [5121.910156,4279.129883,0.14682];
_obj setdir 326.019;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [5091.680176,4277.259766,0.14682];
_obj setposATL [5091.680176,4277.259766,0.14682];
_obj setdir 39.244;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5072.27002,4290.830078,1.88963];
_obj setposATL [5072.27002,4290.830078,1.88963];
_obj setdir 40.29;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5065.709961,4296.319824,0.909149];
_obj setposATL [5065.709961,4296.319824,0.909149];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5065.709961,4296.22998,-1.18976];
_obj setposATL [5065.709961,4296.22998,-1.18976];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5059.290039,4301.709961,0.528625];
_obj setposATL [5059.290039,4301.709961,0.528625];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5059.290039,4301.620117,-1.57028];
_obj setposATL [5059.290039,4301.620117,-1.57028];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5052.75,4307.279785,0.591385];
_obj setposATL [5052.75,4307.279785,0.591385];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5052.75,4307.189941,-1.50752];
_obj setposATL [5052.75,4307.189941,-1.50752];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5046.310059,4312.72998,0.793457];
_obj setposATL [5046.310059,4312.72998,0.793457];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5046.310059,4312.640137,-1.30545];
_obj setposATL [5046.310059,4312.640137,-1.30545];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5039.839844,4318.290039,1.50067];
_obj setposATL [5039.839844,4318.290039,1.50067];
_obj setdir 42.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5039.839844,4318.200195,-0.598236];
_obj setposATL [5039.839844,4318.200195,-0.598236];
_obj setdir 41.52;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5040.490234,4324.529785,0.479874];
_obj setposATL [5040.490234,4324.529785,0.479874];
_obj setdir 308.55;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5040.569824,4324.540039,-1.61903];
_obj setposATL [5040.569824,4324.540039,-1.61903];
_obj setdir 307.119;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5045.459961,4331.189941,1.39207];
_obj setposATL [5045.459961,4331.189941,1.39207];
_obj setdir 308.55;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5045.549805,4331.189941,-0.706833];
_obj setposATL [5045.549805,4331.189941,-0.706833];
_obj setdir 307.119;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5040.439941,4324.52002,2.48312];
_obj setposATL [5040.439941,4324.52002,2.48312];
_obj setdir 309.091;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5050.580078,4337.970215,0.549973];
_obj setposATL [5050.580078,4337.970215,0.549973];
_obj setdir 308.55;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5050.669922,4337.970215,-1.54893];
_obj setposATL [5050.669922,4337.970215,-1.54893];
_obj setdir 307.119;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5055.540039,4344.870117,0.420776];
_obj setposATL [5055.540039,4344.870117,0.420776];
_obj setdir 308.55;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5055.629883,4344.879883,-1.67813];
_obj setposATL [5055.629883,4344.879883,-1.67813];
_obj setdir 307.119;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5060.439941,4351.75,1.75433];
_obj setposATL [5060.439941,4351.75,1.75433];
_obj setdir 308.737;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5060.529785,4351.75,-0.344574];
_obj setposATL [5060.529785,4351.75,-0.344574];
_obj setdir 307.306;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5065.509766,4358.540039,1.2415];
_obj setposATL [5065.509766,4358.540039,1.2415];
_obj setdir 308.737;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5065.589844,4358.549805,-0.857407];
_obj setposATL [5065.589844,4358.549805,-0.857407];
_obj setdir 307.306;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5069.189941,4365.919922,0.465714];
_obj setposATL [5069.189941,4365.919922,0.465714];
_obj setdir 290.137;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5069.27002,4365.950195,-1.63319];
_obj setposATL [5069.27002,4365.950195,-1.63319];
_obj setdir 288.706;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5078.22998,4363.149902,0.465714];
_obj setposATL [5078.22998,4363.149902,0.465714];
_obj setdir 290.137;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5078.319824,4363.180176,-1.63319];
_obj setposATL [5078.319824,4363.180176,-1.63319];
_obj setdir 288.706;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5063.140137,4347.970215,1.74535];
_obj setposATL [5063.140137,4347.970215,1.74535];
_obj setdir 14.611;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5063.180176,4347.890137,-0.353561];
_obj setposATL [5063.180176,4347.890137,-0.353561];
_obj setdir 13.18;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5071.47998,4346.140137,-0.00933838];
_obj setposATL [5071.47998,4346.140137,-0.00933838];
_obj setdir 13.661;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5079.810059,4344.450195,-1.82416];
_obj setposATL [5079.810059,4344.450195,-1.82416];
_obj setdir 13.18;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [0.0,0.0,2.36557];
_obj setposATL [0.0,0.0,2.36557];
_obj setdir 14.819;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5087.950195,4342.77002,-1.37096];
_obj setposATL [5087.950195,4342.77002,-1.37096];
_obj setdir 11.285;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5087.870117,4342.589844,0.719864];
_obj setposATL [5087.870117,4342.589844,0.719864];
_obj setdir 11.493;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5087.830078,4342.669922,2.81877];
_obj setposATL [5087.830078,4342.669922,2.81877];
_obj setdir 12.924;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5092.439941,4347.100098,0.990967];
_obj setposATL [5092.439941,4347.100098,0.990967];
_obj setdir 108.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5092.600098,4347.0,-1.09985];
_obj setposATL [5092.600098,4347.0,-1.09985];
_obj setdir 107.978;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5092.52002,4347.129883,3.08987];
_obj setposATL [5092.52002,4347.129883,3.08987];
_obj setdir 109.617;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5082.0898438,4358.580078,1.28186];
_obj setposATL [5082.0898438,4358.580078,1.28186];
_obj setdir 18.438;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5082.120117,4358.5,-0.817047];
_obj setposATL [5082.120117,4358.5,-0.817047];
_obj setdir 17.007;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [5071.22998,4344.569824,-0.0752563];
_obj setposATL [5071.22998,4344.569824,-0.0752563];
_obj setdir 192.096;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5086.939941,4362.689941,1.35945];
_obj setposATL [5086.939941,4362.689941,1.35945];
_obj setdir 110.816;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5086.850098,4362.660156,-0.739456];
_obj setposATL [5086.850098,4362.660156,-0.739456];
_obj setdir 109.385;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5079.759766,4344.439941,0.221039];
_obj setposATL [5079.759766,4344.439941,0.221039];
_obj setdir 14.475;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5079.669922,4344.390137,2.22394];
_obj setposATL [5079.669922,4344.390137,2.22394];
_obj setdir 14.031;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5092.939941,4364.430176,1.35945];
_obj setposATL [5092.939941,4364.430176,1.35945];
_obj setdir 19.249;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5092.970215,4364.339844,-0.739456];
_obj setposATL [5092.970215,4364.339844,-0.739456];
_obj setdir 17.818;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5101.0200195,4361.990234,0.862366];
_obj setposATL [5101.0200195,4361.990234,0.862366];
_obj setdir 19.249;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5101.0498047,4361.910156,-1.23654];
_obj setposATL [5101.0498047,4361.910156,-1.23654];
_obj setdir 17.818;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5109.189941,4359.600098,0.602676];
_obj setposATL [5109.189941,4359.600098,0.602676];
_obj setdir 19.409;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5109.220215,4359.52002,-1.49623];
_obj setposATL [5109.220215,4359.52002,-1.49623];
_obj setdir 17.979;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5116.160156,4354.640137,1.23218];
_obj setposATL [5116.160156,4354.640137,1.23218];
_obj setdir 56.751;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5116.140137,4354.560059,-0.86673];
_obj setposATL [5116.140137,4354.560059,-0.86673];
_obj setdir 55.321;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5121.209961,4347.910156,2.58463];
_obj setposATL [5121.209961,4347.910156,2.58463];
_obj setdir 56.751;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5121.189941,4347.830078,0.485718];
_obj setposATL [5121.189941,4347.830078,0.485718];
_obj setdir 55.321;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5121.0898438,4347.97998,-1.59563];
_obj setposATL [5121.0898438,4347.97998,-1.59563];
_obj setdir 54.274;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5126.22998,4341.0600586,1.37897];
_obj setposATL [5126.22998,4341.0600586,1.37897];
_obj setdir 55.321;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5131.149902,4334.310059,1.37897];
_obj setposATL [5131.149902,4334.310059,1.37897];
_obj setdir 55.321;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5126.220215,4341.0800781,-0.676407];
_obj setposATL [5126.220215,4341.0800781,-0.676407];
_obj setdir 56.706;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5131.180176,4334.390137,3.47787];
_obj setposATL [5131.180176,4334.390137,3.47787];
_obj setdir 56.751;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5131.0600586,4334.47998,-0.702377];
_obj setposATL [5131.0600586,4334.47998,-0.702377];
_obj setdir 54.274;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5134.149902,4327.359863,-0.718185];
_obj setposATL [5134.149902,4327.359863,-0.718185];
_obj setdir 79.818;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5134.470215,4318.830078,2.19699];
_obj setposATL [5134.470215,4318.830078,2.19699];
_obj setdir 98.066;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5134.850098,4321.620117,-2.12158];
_obj setposATL [5134.850098,4321.620117,-2.12158];
_obj setdir 91.128;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5098.75,4349.129883,-1.31331];
_obj setposATL [5098.75,4349.129883,-1.31331];
_obj setdir 13.391;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5098.709961,4349.140137,0.7686];
_obj setposATL [5098.709961,4349.140137,0.7686];
_obj setdir 13.391;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [5124.97998,4340.359863,-0.0752563];
_obj setposATL [5124.97998,4340.359863,-0.0752563];
_obj setdir 233.517;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Tower_V3_F" createvehicle [5064.240234,4327.0800781,0];
_obj setposATL [5064.240234,4327.0800781,0];
_obj setdir 13.427;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_HQ_V3_F" createvehicle [5105.470215,4292.870117,0.531143];
_obj setposATL [5105.470215,4292.870117,0.531143];
_obj setdir 91.037;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_House_V3_F" createvehicle [5123.97998,4309.259766,0.662964];
_obj setposATL [5123.97998,4309.259766,0.662964];
_obj setdir 94.951;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "b_ArundoD2s_F" createvehicle [5110.180176,4354.669922,1.31424];
_obj setposATL [5110.180176,4354.669922,1.31424];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "b_ArundoD2s_F" createvehicle [5115.890137,4347.22998,2.16002];
_obj setposATL [5115.890137,4347.22998,2.16002];
_obj setdir 360;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HelipadCircle_F" createvehicle [5109.0698242,4317.0600586,-1.02455];
_obj setposATL [5109.0698242,4317.0600586,-1.02455];
_obj setdir 288.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Flag_White_F" createvehicle [5091.0898438,4342.290039,4.96854];
_obj setposATL [5091.0898438,4342.290039,4.96854];
_obj setdir 360;
_obj setFlagTexture "client\images\promoteTextures\A51flag.paa";
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5071.509766,4373.910156,-0.575363];
_obj setposATL [5071.509766,4373.910156,-0.575363];
_obj setdir 288.706;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5080.879883,4371.180176,-0.435379];
_obj setposATL [5080.879883,4371.180176,-0.435379];
_obj setdir 288.879;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_Patrol_V3_F" createvehicle [5085.109863,4370.879883,-0.295837];
_obj setposATL [5085.109863,4370.879883,-0.295837];
_obj setdir 197.145;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_HBarrierBig_F" createvehicle [5134.0600586,4327.330078,1.23599];
_obj setposATL [5134.0600586,4327.330078,1.23599];
_obj setdir 79.818;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
